### ISSUE TITLE
How to create two request with diff params?

### ISSUE THREAD

**Issue by alexesDev** [lexich/redux-api#115]
I try run a code like this... and one of two requests canceled...
```js
dispatch(rest.actions.products({ categoryId: 2 }));
dispatch(rest.actions.products({ categoryId: 10 }));
```

I find this code... https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L123
```
      const isLoading = get(state, prefix, reducerName, "loading");
      if (isLoading) {
        return;
      }
```

I cannot create parallel request to one resource with ```redux-api```. Right?

**Comment by lexich** [comment]
Yes. Because it's false behaviour update state in paraller. If you want to make simple xhr requests without update state, you should use helper request.

```js
rest.actions.products.request({ categoryId: 2 });
rest.actions.products.request({ categoryId: 10 });
```

**Comment by alexesDev** [comment]
I do not know how to do, but temporary solution look like this...
```js
const GREP_PRODUCTS_SUCCESS = 'GREP_PRODUCTS_SUCCESS';

const rest = reduxApi({
  products: {
    //...
    reducer(state, action) {
      if (action.type === GREP_PRODUCTS_SUCCESS) {
        return { ...state,  data: uniqBy([...action.data, ...state.data], 'id') };
      }

      return state;
    },
  },
});

export const grepProducts = (...args) => {
  return (dispatch) => {
    rest.actions.products.request(...args).then((data) => {
      dispatch({
        type: GREP_PRODUCTS_SUCCESS,
        data: transformer(data),
      });
    });
  };
};

**Comment by lexich** [comment]
I think that it's good solution. But I think you should update sync flag.

**Comment by alexesDev** [comment]
And another problem with
```
if (isLoading) {
    return;
}
```
User load /lexich/codemirror-hql and immediately load /lexich/css-image... and sees nothing (with slow internet). Its very unexpected behavior...
![example](https://i.imgbox.com/3UfGvpg7.png)

**Comment by lexich** [comment]
You need reset request https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#resetmutation but isLoading flag it's interesting point. Maybe it's needed to add isLoading: false to here https://github.com/lexich/redux-api/blob/master/src/reducerFn.js#L42

**Comment by KODerFunk** [comment]
I have a similar problem. I think it is not right to keep in the Redux-State one branch to the resource-point, the branches should be different for different `pathvars`.
The problem may be that that connection is going component and defining paths within the component.
This is a huge problem for use in medium and large applications. Now I feel pain work on dependent on server-sync React-Native application.
What do we do? :)

**Comment by lexich** [comment]
@koderfunk can you some examples of your problems.

**Comment by KODerFunk** [comment]
@lexich sure, can extend example of @alexesDev:

Products and Categories have many-to-many relations. Product-item have `category_ids: [2, 10, 15]` in response from server.
```javascript
reduxApi({
  categories: 'categories/:id',
  products: 'categories/:category_id/products/:id',
})
```
Scenario:
1) Start App, open first screen with categories, sync categories collection, it shown, all right.
2) Tap on category with `id: 2`, open second screen with products of this category (loading after mounting component).
3) Back to first screen (without remounting, because screens stacking as history), and tap category with `id: 10`, open second screen with products of this category.

Business-conventions of many applications mean is not rapid obsolescence of data and require semi-offline work of applications.

Impossible cases with current concept of storing and connection:
'4) **Network abused**: Go back to first screen, and repeat step 2. Collection of products for category-2 erased (at 3rd step), see **loading state again**, although that a few seconds ago products for this category is already loaded!
'5) **Broken navigation**: on second screen, scroll down big distance, in each product-card shown (as tag-marks) categories selected by category_ids, tap on category-mark with id=15 must open next history screen, second instance of `ProductsScreen` in navigator. New products collection loaded and erased previous. Go back, **reloading, scroll position dropped**.
'6) **Can't offline**: cant normal use any redux-storage for organize persisted user-scoped data-replication for transparent browsing data (without loading state when browse replicated data) and lazy-fetching (refreshing) in background.

What need:

1. Success timestamp, to make a decision about reloading stored collection.
2. Add additional level in redux store for split parametrized collections and items by keys generated from `pathvars`.
```json
{ 
  "categories": { "sync": true, "data": "..." },  
  "products": { 
    "category_id_2": { "sync": true, "data": "..." }, 
    "category_id_15": { "...": "..." },
    "category_id_15_city_2": { "...": "..." }
   }
}
```
3. More advanced connection to react-components, with describing `pathvars` on react-level, but provide selecting from store on redux-connect level. (Compatibility with the current props-usage)

**Comment by lexich** [comment]
@koderfunc thx for your very good ideas. I think that after holidays i tried to implement some of them except react integration. This functionality should implement external library and it's another story.

**Comment by alexesDev** [comment]
Hi. nothing new? :sleeping:

**Comment by lexich** [comment]
Unfortunately nothing new. @KODerFunk have started implement this in fork, but there aren't any PR :(

**Comment by lexich** [comment]
@alexesDev @KODerFunk  I publish new release with cache support https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#cache v0.10.2

I think about new feature `compose` - union of data that you can get from cache

**Comment by alexesDev** [comment]
@lexich Maybe you should choose another way for features like cache?

external lib
```js
function permanent({ currentData, cancel }) {
  if (currentData) {
    cancel();
  }
}

function cache({ someting data }) {
  // cache logic
}
```

and use
```js
import cache from 'redux-api-cache';
import permanent from 'redux-api-permanent';

permanent: {
  url: "/api/v1/permanent/1",
  prefetch: [permanent]
},
expires1: {
  url: "/api/v1/permanent/1",
  prefetch: [cache]
}
```

**Comment by alexesDev** [comment]
@lexich like express/redux middleware

**Comment by alexesDev** [comment]
@lexich and extract options like crud to pure functions
```js
products: withCrud({
  url: '/products',
}),

// with-crud.js
const CRUD = ...

function crud(options) {
  return {
    ...options,
    helpers: [...CRUD, ...options.helpers],
  };
}
```

**Comment by lexich** [comment]
@alexesDev About cache it's interesting idea.
Current solution allow to use external solution for cache redux state. But maybe it's good idea to make this behaviour customisable.

About Crud I think that you can do this with current functionality and maybe it'll be useful to make crud helpers, but not strongly necessary

**Comment by alexesDev** [comment]
@lexich I mean crud options

**Comment by gormonn** [comment]
Do you have any news?
