### ISSUE TITLE
Use with immutablejs

### ISSUE THREAD

**Issue by dagda1** [lexich/redux-api#159]
Is it possible to use redux-api with immutablejs?

are there any examples?

**Comment by lexich** [comment]
Hi @dagda1 
You don't need to use immutablejs in redux-api because state update without mutation and only by server. You should only read data or ask server to update it. 
But redux-api it's only thin wrapper around redux and Xhr. And if you want to use immutablejs in you redux reducers you can do it [ReduxDocs](http://redux.js.org/docs/recipes/UsingImmutableJS.html)

**Comment by deevus** [comment]
You can use `fromJS` as the `transformer` so at least `data` will be immutable.
