### ISSUE TITLE
No Introduction in README.md

### ISSUE THREAD

**Issue by barrystaes** [lexich/redux-api#41]
The readme has detailed API docs to tell me how to use `redux-api`. But it does not introduce it. 

- What is `redux-api` for, 
- what problem does it solve, and 
- why i should want to use `redux-api` to solve that?

I just found it due to its name (API and Redux) but i'm still not sure what it does exactly.. whether it is what i was looking for.

**Comment by barrystaes** [comment]
Other question might be answered there;

- Can i use it for optimistic UI updates? When deleting an item?
- Can i use it when i already have API fetch routines?
- Can i use it for GET POST PUT DELETE and PATCH?
- Can i use it for JSON only?

Where they are located now, the API docs add more confusion than they prevent. I suggest keeping the example there, but moving the API docs to a seperate file like `USAGE.md`.

**Comment by barrystaes** [comment]
I made a start in https://github.com/barrystaes/redux-api/tree/fix-docs

If anyone is willing to answer the questions above, i'd be happy to provide a PR.

**Comment by lexich** [comment]
You are right, I have problem with description in Readme. 
redux-api - it's wrapper around redux infrastructure to generate actions and reduces with AJAX calls.

Can i use it for optimistic UI updates? When deleting an item? 
If you make ajax call of course, otherwise you can use simple redux actions/reducers.

Can i use it when i already have API fetch routines?
You can rewrite you code or make it legacy and write new API with redux-api

Can i use it for GET POST PUT DELETE and PATCH?
redux-api make ajax call throw adapters. Recomends way is to using fetch api. And you can configure you call as you want.

Can i use it for JSON only?
JSON only for default adapter, but it's a pretty simple function. And anyone can write his own adapter

Can i use it with normalizr later?
I haven't XP with normalizr, but as i understand, you can use it in `transformer` callback

**Comment by barrystaes** [comment]
Thanks for your answer. Could you elaborate more on 

- the problem that it can fix
- how it fixes that, and with what approach

And how would you say it compares to https://github.com/Versent/redux-crud and https://github.com/pauldijou/redux-act ?

**Comment by lexich** [comment]
It's very fun, because all this projects were started in august 2015 (12, 15, 19).

"redux-crud" delivers lightweight helpers for generate actions and reducers. Very simple. It's a good and a bad part of this library, because you need to write a lot of boilerplate code.

"redux-act" is another view to redux, but this lib don't solve problem ajax calls.

"redux-api" is solving problem "Ajax request in redux infrastructure". You don't need to write a lot of boilerplate to send/get data from backend. For very simple request you need to write only

```js
reduxApi({
  test: "/api/test"
});
```

But in real world is more complex. For example you need to make request but for this you need information from another or you should to do anythink after success responce. redux-api provide this functionality.

**Comment by lexich** [comment]
> Can i use it for optimistic UI updates? When deleting an item? 
#42

**Comment by istinspring** [comment]
More examples would be nice. 

Questions still actual for me:

+ How to mutate state? Detailed examples with **broadcast** and **virtual**
+ Is it possible to process onSuccess and onFail after dispatch?

if i need to close modal (i.e. this.setState( {...} ))
How can i do it after dispatch?
```
dispatch(rest.actions.campaignsList)
```

**Comment by lexich** [comment]
@istinspring I update documentation. It has some information and examples for you
https://github.com/lexich/redux-api/blob/master/DOCS.md#virtual
https://github.com/lexich/redux-api/blob/master/DOCS.md#events
